-- ============================================================
-- AML Smurfing Detection
-- Rule: STRUCTURING
-- ============================================================

-- İş mantığı:
-- Aynı gönderen hesaptan 24 saat içinde,
-- her biri 10.000'in altında,
-- en az 3 CASH_IN / TRANSFER işlemi.

CREATE OR REPLACE VIEW STG_AML.STRUCTURING_SCORE_VW AS
SELECT
    GONDEREN_HESAP AS HESAP,
    ISLEM_TARIHI,

    COUNT(*) OVER (
        PARTITION BY GONDEREN_HESAP
        ORDER BY ISLEM_TARIHI
        RANGE BETWEEN INTERVAL '24' HOUR PRECEDING AND CURRENT ROW
    ) AS ISLEM_SAYISI_24S,

    SUM(TUTAR) OVER (
        PARTITION BY GONDEREN_HESAP
        ORDER BY ISLEM_TARIHI
        RANGE BETWEEN INTERVAL '24' HOUR PRECEDING AND CURRENT ROW
    ) AS TOPLAM_TUTAR_24S

FROM STG_AML.STG_PARA_TRANSFERLERI
WHERE TIP IN ('CASH_IN', 'TRANSFER')
  AND TUTAR < 10000;


-- CKM entegrasyonu

INSERT INTO STG_AML.E$_PARA_TRANSFERLERI
SELECT
    t.*,
    'STRUCTURING_PATTERN_DETECTED',
    s.ISLEM_SAYISI_24S,
    NULL
FROM STG_AML.STG_PARA_TRANSFERLERI t
JOIN STG_AML.STRUCTURING_SCORE_VW s
    ON t.GONDEREN_HESAP = s.HESAP
   AND t.ISLEM_TARIHI = s.ISLEM_TARIHI
WHERE s.ISLEM_SAYISI_24S >= 3;